stages:
  - build
  - deploy

build-react-app:
  image: node:14-alpine
  stage: build
  script:
    - npm ci
    - CI=false npm run build
  artifacts:
    paths:
      - build

deploy-to-s3:
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH 
  image:
    name: amazon/aws-cli:2.6.4
    entrypoint: [""]
  script:
    - aws --version
    - echo "Being deployed to S3 ..."
    - aws s3 sync build s3://$AWS_S3_BUCKET_NAME --delete