export const GET_PROGRAMS = 'PROGRAMS/GET_ALL';
export const GET_PROGRAMS_LOADING = 'PROGRAMS/GET_ALL_LOADING';
export const GET_PROGRAMS_SUCCESS = 'PROGRAMS/GET_ALL_SUCCESS';
export const GET_PROGRAMS_FAIL = 'PROGRAMS/GET_ALL_FAIL';