export const GET_ALL_PROGRAMS_LOADING = 'PROGRAMS/GET_ALL_LOADING';
export const GET_ALL_PROGRAMS_SUCCESS = 'PROGRAMS/GET_ALL_SUCCESS';
export const GET_ALL_PROGRAMS_FAIL = 'PROGRAMS/GET_ALL_FAIL';

export const GET_PROGRAM_REVIEWS_LOADING = 'PROGRAMS/GET_PROGRAM_REVIEWS_LOADING';
export const GET_PROGRAM_REVIEWS_SUCCESS = 'PROGRAMS/GET_PROGRAM_REVIEWS_SUCCESS';
export const GET_PROGRAM_REVIEWS_FAIL = 'PROGRAMS/GET_PROGRAM_REVIEWS_FAIL';

export const SEARCH_PROGRAMS = 'PROGRAMS/SEARCH_PROGRAMS';
export const FILTERED_PROGRAMS = 'PROGRAMS/FILTERED_PROGRAMS';
